export const AppUrl ={
	// Url Publiques
	HOME: "/",
	LOGIN: "/auth/login",
	REGISTER: "/register",
	FORGOT_PASSWORD: "/forgot-password",

	// Tout le reste a besoin d'authentification
	DASHBOARD: "/sales/dash",
	WELCOME: "/welcome",
	ABOUT: "/about",
	CLIENTS: "/sales/clients",
	QUOTES: "/quotes",
	TENDERS: "/tenders",
	SUPPLIERS: "/suppliers",
	CLIENT:"/clients",
	INFOPROPO:"/sales/listeProforma",
	PROPO:'/sales/proposition',
	ORDER:'/sales/order',
	ORDERINFO:'/sales/infoCommande',
	INVOICE:'/sales/invoice',
	INVOICEINFO:'/sales/recapFacture',
	DELIVERY:'/sales/livraison',
	DELIVERYINFO:'/sales/listeLivraison',
	SCHEDULE:'/sales/echeanceCreate',
	SCHEDULEINFO:'/sales/echeanceListe',
	SALES: "/sales",
	BALANCE:"/sales/bilan",
	STATS:'/sales/statistique',
	FOLLOWUP: "/followup",
	USERS: "/users",
	TENDERS_DOCUMENTS: "/tenders/documents",
	TENDERS_SUBMISSIONS: "/tenders/submissions",
	TENDERS_PROJECTS: "/tenders/projects",
	SUPPLIERS_CONTACTS: "/suppliers/contacts",
	SUPPLIERS_COMMANDS: "/suppliers/commands",
	SUPPLIERS_CONTRACTS: "/suppliers/contracts",
	SUPPLIERS_DOCUMENTS: "/suppliers/documents",
	SUPPLIERS_INVOICES: "/suppliers/invoices",
	SUPPLIERS_EVALUATIONS: "/suppliers/evaluations",
	MAINTENANCE_TICKETS: "/maintenance/tickets",
	MAINTENANCE_PLANNING: "/maintenance/planning",
	MAINTENANCE_EQUIPMENTS: "/maintenance/equipements",
	MAINTENANCE_CONTRACTS: "/maintenance/contracts",
	MAINTENANCE_REPORTS: "/maintenance/reports",

	// TENDERS
	TENDERS_TASK_FORM: "tenders/task-form"
} as const;